#!/usr/bin/env bash
# =============================================================================
# lsbx Carnyx migration: CUTOVER (per MIGRATION-CARNYX.md §10 + §11)
#
# Safe, mostly-idempotent. Prints a start/end guard wall so an operator can
# see exactly what ran. Provides an explicit rollback (--rollback) using the
# unit files preserved in the backup dir. Does NOT touch the old Python
# systemd unit files (they are merely disabled, not deleted) and does NOT
# delete the old Python state dir / checkout — §14 decommission is separate
# and intentionally deferred.
#
# Prereq: sudo. You'll be prompted once for your password and it's cached
# for the script's duration (no passwordless sudo required).
# =============================================================================
set -uo pipefail

# ---- configuration (edit if paths differ on your host) ----------------------
BACKUP_DIR="/home/carnyx/lsbx-migration-backup-20260825T162643Z"
NEW_UNITS_DIR="/home/carnyx/lsbx-state/systemd-units"     # generated by `lsbx bootstrap`
OLD_DETACHED_BROKER_PID=1529305                            # the non-systemd Python ci_broker
GOLDEN_DIR="/home/carnyx/ISOs/images/goldens"             # kept by BOTH old & new systems
GATEWAY_HOST="100.125.210.60"
GATEWAY_PORT="8243"
# the .env files referenced by the new units:
NEW_SERVE_ENV="/home/carnyx/lsbx-state/serve.env"
NEW_BROKER_ENV="/home/carnyx/ISOs/images/ci-broker.env"

log()  { printf '### %s\n' "$*"; }
die()  { printf 'FATAL: %s\n' "$*" >&2; exit 1; }

# ---- sanity: required files ------------------------------------------------
[ -d "$BACKUP_DIR" ]               || die "backup dir $BACKUP_DIR not found"
[ -d "$NEW_UNITS_DIR" ]            || die "new units dir $NEW_UNITS_DIR not found"
[ -f "$NEW_UNITS_DIR/lsbx-serve.service" ]    || die "no lsbx-serve.service in $NEW_UNITS_DIR"
[ -f "$NEW_UNITS_DIR/lsbx-ci-broker.service" ]|| die "no lsbx-ci-broker.service in $NEW_UNITS_DIR"
[ -f "$NEW_SERVE_ENV" ]            || die "serve env $NEW_SERVE_ENV not found"
[ -f "$NEW_BROKER_ENV" ]           || die "broker env $NEW_BROKER_ENV not found"
command -v sudo >/dev/null         || die "sudo not available"
echo "One-time sudo check (you'll be prompted for your password)..."
sudo -v 2>/dev/null && log "sudo OK" || die "sudo failed (wrong password or no privileges)"

# ---- display plan ----------------------------------------------------------
log "=== LSBX MIGRATION CUTOVER ==="
log "Will stop old systemd units: lsbx-gateway, lsbx-stream-proxy, lsbx-ci-broker"
log "Will kill detached old Python broker PID $OLD_DETACHED_BROKER_PID (if present & is ci_broker)"
log "Will install + enable + start new: lsbx-serve.service, lsbx-ci-broker.service"
log "Will run post-cutover verification against http://$GATEWAY_HOST:$GATEWAY_PORT"

# ---- ROLLBACK short-circuit ------------------------------------------------
if [[ "${1:-}" == "--rollback" ]]; then
  log "=== ROLLBACK ==="
  sudo systemctl stop lsbx-serve.service lsbx-ci-broker.service 2>/dev/null || true
  sudo systemctl disable lsbx-serve.service 2>/dev/null || true
  # new ci-broker unit overwrote the same path; restore the ORIGINAL backup before re-enabling
  sudo cp "$BACKUP_DIR/lsbx-ci-broker.service" /etc/systemd/system/lsbx-ci-broker.service
  sudo cp "$BACKUP_DIR/lsbx-gateway.service"    /etc/systemd/system/lsbx-gateway.service
  sudo cp "$BACKUP_DIR/lsbx-stream-proxy.service" /etc/systemd/system/lsbx-stream-proxy.service
  sudo systemctl daemon-reload
  sudo systemctl enable  lsbx-gateway.service lsbx-stream-proxy.service lsbx-ci-broker.service
  sudo systemctl start   lsbx-gateway.service lsbx-stream-proxy.service lsbx-ci-broker.service
  sleep 3
  sudo systemctl status  lsbx-gateway.service lsbx-stream-proxy.service lsbx-ci-broker.service --no-pager || true
  OLD_TOK=$(grep -oP '(?<=GATEWAY_TOKEN=).*' "$BACKUP_DIR/.env" 2>/dev/null || true)
  log "old /health:"
  curl -sf -m 10 -H "Authorization: Bearer $OLD_TOK" "http://$GATEWAY_HOST:$GATEWAY_PORT/health" || die "old gateway /health FAILED after rollback"
  log "=== rollback complete — old Python system is back ==="
  exit 0
fi

# ---- step 1: confirm the CI queue is empty (do not cut over mid-job) -------
pending=$(gh run list --repo lufs-audio/lufs-sandbox-server --limit 30 \
          --json status --jq '[.[] | select(.status=="in_progress" or .status=="queued" or .status=="pending")] | length' 2>/dev/null || echo "ERR")
if [[ "$pending" == "ERR" ]]; then
  log "WARNING: could not query GitHub run queue (gh may need auth). Not blocking, but VERIFY manually before relying on the broker."
elif [[ "$pending" -gt 0 ]]; then
  die "CI queue has $pending in-flight/queued run(s). Abort — drain before cutover."
else
  log "CI queue empty (0 pending)."
fi

# ---- step 2: stop old systemd services ------------------------------------
log "Stopping old systemd services..."
sudo systemctl stop lsbx-gateway.service lsbx-stream-proxy.service lsbx-ci-broker.service 2>/dev/null || true
sudo systemctl disable lsbx-gateway.service lsbx-stream-proxy.service lsbx-ci-broker.service 2>/dev/null || true

# ---- step 3: stop the DETACHED old Python ci_broker (not under systemd) ----
if kill -0 "$OLD_DETACHED_BROKER_PID" 2>/dev/null; then
  # guard: only kill if it is actually the ci_broker (never a random pid)
  if tr '\0' ' ' < "/proc/$OLD_DETACHED_BROKER_PID/cmdline" 2>/dev/null | grep -q 'lufs_sandbox.ci_broker'; then
    log "Killing detached old Python ci_broker (PID $OLD_DETACHED_BROKER_PID)..."
    kill "$OLD_DETACHED_BROKER_PID" && log "  sent SIGTERM (will confirm gone below)"
    sleep 2
    kill -0 "$OLD_DETACHED_BROKER_PID" 2>/dev/null && { log "  still alive; sending SIGKILL"; kill -9 "$OLD_DETACHED_BROKER_PID" 2>/dev/null || true; }
  else
    die "PID $OLD_DETACHED_BROKER_PID is NOT the ci_broker — refusing to kill it. Recheck manually."
  fi
else
  log "PID $OLD_DETACHED_BROKER_PID not running — good (detached broker already gone)."
fi

# ---- step 4: install + enable + start the new services ----------------------
log "Installing new units..."
sudo cp "$NEW_UNITS_DIR/lsbx-serve.service"      /etc/systemd/system/lsbx-serve.service
sudo cp "$NEW_UNITS_DIR/lsbx-ci-broker.service"  /etc/systemd/system/lsbx-ci-broker.service
sudo systemctl daemon-reload
sudo systemctl enable lsbx-serve.service lsbx-ci-broker.service
log "Starting new services..."
sudo systemctl start lsbx-serve.service
sudo systemctl start lsbx-ci-broker.service

# ---- step 5: verification ---------------------------------------------------
log "Waiting for services..."
sleep 3
log "=== lsbx-serve.service status ==="
systemctl status lsbx-serve.service --no-pager || true
log "=== lsbx-ci-broker.service status ==="
systemctl status lsbx-ci-broker.service --no-pager || true

NEW_TOK=$(sed -n 's/^LSBX_GATEWAY_TOKEN=//p' "$NEW_SERVE_ENV")
log "=== new gateway /health === (expect Rust backend, profiles ci/default/desktop/web/win11)"
curl -s -m 10 -H "Authorization: Bearer $NEW_TOK" "http://$GATEWAY_HOST:$GATEWAY_PORT/health" && echo
if ! curl -sf -m 10 -H "Authorization: Bearer $NEW_TOK" "http://$GATEWAY_HOST:$GATEWAY_PORT/health" >/dev/null 2>&1; then
  log "WARNING: new gateway /health not OK. New units may be crash-looping."
  log "       See SR.11 rollback: run with --rollback, or investigate (do NOT debug under production pressure)."
else
  log "SUCCESS: new gateway /health is OK."
fi

log
log "=== CUTOVER SCRIPT COMPLETE ==="
log "Next (operator): run the §11 functional round-trip (create/exec/destroy via REST), the"
log "CI broker smoke workflow, and the desktop-console smoke, and paste results back."
log "If anything did NOT come up, re-run this script with --rollback."