//! Guest-command execution over SSH — the *other* kind of SSH this crate
//! needs (see `crate::transport` module docs for the distinction).
//!
//! `Backend::run`/`put_file`/`get_file` always execute inside the guest VM
//! over the guest's own SSH server, completely independent of whether the
//! libvirt host managing that guest is local or remote — a guest VM always
//! needs its own SSH reachability regardless of where its hypervisor lives.
//! This is exactly the layer the unit contract's explicit "batch-mode SSH
//! with stdin isolation (`/dev/null`) for non-interactive commands"
//! acceptance criterion is about.
//!
//! ## Mechanism choice: shelling out to the system `ssh`/`scp`, not `russh`
//!
//! Candidate A shelled out to the system `ssh`/`scp` binaries with
//! `-o BatchMode=yes` and `Stdio::null()` on stdin. That mechanism is kept
//! here (adapted, not copied verbatim — Candidate A's version referenced
//! request fields that don't exist on the real `Backend` trait). The
//! alternative, doing this with `russh` instead of shelling out, is
//! explicitly left open by the unit's own brief ("adapt Candidate A's
//! shelling-out approach or implement equivalent behavior with `russh`,
//! your choice"). Shelling out was chosen over `russh` for this unit
//! because:
//!
//! - It gets the exact, well-tested `BatchMode=yes` semantics (fail fast
//!   with a clear error whenever a passphrase/host-key/interactive prompt
//!   would otherwise be needed) directly from OpenSSH itself, rather than
//!   reimplementing that "never prompt, never block" contract by hand
//!   against `russh`'s lower-level API.
//! - `scp`'s (or `sftp`'s) file-transfer semantics for `put_file`/
//!   `get_file` are directly available without hand-rolling SFTP framing.
//! - The known cost — an extra process per call, and depending on the
//!   `ssh`/`scp` binaries being present on the host running `lsbx` — is
//!   judged acceptable here since this backend already shells out to
//!   `qemu-img` for the exact same "no mature enough pure-Rust option
//!   justifies the complexity" reason (SPEC.md Deviation 7).
//!
//! A `russh`-based reimplementation of this module would be a reasonable
//! follow-up if the `ssh`/`scp` binary dependency becomes a real deployment
//! problem; nothing in `Backend`'s public contract here depends on which
//! mechanism is used internally.
//!
//! ## Host key verification
//!
//! This module intentionally passes `-o StrictHostKeyChecking=accept-new`
//! (accept and pin an unseen host key, but still fail on a *changed* one)
//! rather than `-o StrictHostKeyChecking=no` (silently accept anything,
//! every time) — but, matching the Python reference's libvirt backend
//! (`libvirt.py`'s `_key_flags`), pairs it with
//! `-o UserKnownHostsFile=/dev/null`. Ephemeral, freshly-created VMs have
//! never been seen before, so `StrictHostKeyChecking=yes` would never
//! succeed; and because libvirt's DHCP pool recycles IPs across sandbox
//! lifetimes, a *new* VM frequently reuses an IP a previous VM held, so a
//! persistent `known_hosts` file would trip "host key changed" on the very
//! first connect (the old entry pinned the previous VM's key). Pointing
//! known-host storage at `/dev/null` keeps `accept-new`'s never-fail-on-new
//! semantics while discarding host keys with the sandbox — the same policy
//! the reference implementation uses.

use lsbx_kernel::error::LsbxError;
use std::path::Path;
use std::process::Stdio;
use tokio::process::Command;

/// SSH connection parameters needed to reach a guest VM. Distinct from
/// [`crate::transport::LibvirtTransport`] on purpose — this describes the
/// guest's own reachability, not the hypervisor's.
#[derive(Debug, Clone)]
pub struct GuestSshTarget<'a> {
    /// Hostname or IP address of the guest (resolved by the caller — this
    /// module does not do libvirt DHCP-lease lookups or DNS resolution).
    pub host: &'a str,
    /// Guest username to authenticate as.
    pub username: &'a str,
    /// Path to the private key to authenticate with (the ephemeral key
    /// generated by Unit 03 for this sandbox).
    pub identity_file: &'a Path,
}

const SSH_CONNECT_TIMEOUT_SECS: u64 = 10;

/// Base batch-mode SSH arguments shared by every non-interactive
/// invocation: never prompt, never inherit anything that could hang
/// waiting on a human, and bound the TCP-connect phase itself so an
/// unreachable guest fails fast rather than hanging on the network layer
/// (separately from whatever `timeout` the caller applies to the whole
/// child process).
fn base_ssh_args(target: &GuestSshTarget<'_>) -> Vec<std::ffi::OsString> {
    vec![
        "-o".into(),
        "BatchMode=yes".into(),
        "-o".into(),
        "StrictHostKeyChecking=accept-new".into(),
        "-o".into(),
        format!("ConnectTimeout={SSH_CONNECT_TIMEOUT_SECS}").into(),
        "-o".into(),
        "UserKnownHostsFile=/dev/null".into(),
        "-o".into(),
        "ClearAllForwardings=yes".into(),
        "-i".into(),
        target.identity_file.as_os_str().to_owned(),
    ]
}

/// Maps a process-level failure (spawn failure, non-zero exit, or a
/// deadline that fired) to the appropriate `LsbxError` variant.
///
/// `exit_code == 255` is OpenSSH's own convention for "the client itself
/// failed" (connection refused, host unreachable, auth rejected, DNS
/// failure) as opposed to a remote command that ran and exited non-zero on
/// its own — mapped to `BackendUnavailable` since that's a transport-level
/// failure to reach the guest, not a report about what the requested
/// command did once it *did* run (which is left in `CommandOutput` for the
/// caller to interpret, not reinterpreted as an `LsbxError` here).
fn is_ssh_client_failure(exit_code: Option<i32>) -> bool {
    exit_code == Some(255)
}

/// POSIX-shell-quotes a single argv element so the guest shell re-parses it
/// as one token. The safe charset (no quoting needed) mirrors `shlex.quote`'s
/// conservative default; anything else is single-quoted with embedded quotes
/// escaped the standard `'…'\''…'` way. An empty string becomes `''`.
fn shell_quote(arg: &str) -> String {
    if !arg.is_empty()
        && arg
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b"@%+=:,./-_".contains(&b))
    {
        return arg.to_string();
    }
    let mut out = String::from("'");
    let mut parts = arg.split('\'');
    if let Some(first) = parts.next() {
        out.push_str(first);
    }
    for part in parts {
        out.push_str("'\\''");
        out.push_str(part);
    }
    out.push('\'');
    out
}

/// Joins an argv array into a single shell command line, quoting each
/// element with [`shell_quote`], for use as ssh's one remote-command
/// argument.
fn shell_quote_join(command: &[String]) -> String {
    command
        .iter()
        .map(|c| shell_quote(c))
        .collect::<Vec<String>>()
        .join(" ")
}

/// Runs `command` inside the guest over batch-mode SSH, with stdin
/// isolated from `/dev/null` — the acceptance criterion this module exists
/// to satisfy. `command` is an argv array; because OpenSSH's client only
/// accepts a single remote *command line* (it concatenates trailing argv
/// with spaces and the guest shell re-parses it — there is no
/// exec-argv-array transport), the argv is reconstructed into one
/// faithfully-quoted shell command via [`shell_quote`]/[`shell_quote_join`]
/// before being passed to `ssh` as a single element. Without that quoting,
/// a conventional `["sh", "-c", "git --version"]` healthcheck would arrive
/// in the guest as `sh -c git --version` and execute `sh -c git` with
/// `--version` in `$0` — `git` printing usage and exiting 1 — exactly the
/// argv-collapse hazard the Python reference avoids by accepting its
/// command as a single pre-joined string.
pub async fn run_command(
    target: &GuestSshTarget<'_>,
    command: &[String],
    timeout: std::time::Duration,
) -> Result<lsbx_kernel::backend::CommandOutput, LsbxError> {
    let mut args = base_ssh_args(target);
    args.push(format!("{}@{}", target.username, target.host).into());
    args.push(shell_quote_join(command).into());

    let child = Command::new("ssh")
        .args(&args)
        .stdin(Stdio::null()) // never inherit the caller's stdin — the acceptance criterion.
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| LsbxError::BackendUnavailable(format!("failed to spawn ssh: {e}")))?;

    let output = match tokio::time::timeout(timeout, child.wait_with_output()).await {
        Ok(Ok(output)) => output,
        Ok(Err(e)) => {
            return Err(LsbxError::BackendUnavailable(format!(
                "ssh process I/O failed: {e}"
            )))
        }
        Err(_) => {
            return Err(LsbxError::Interrupted(format!(
                "ssh command timed out after {timeout:?}"
            )))
        }
    };

    let exit_code = output.status.code();
    if is_ssh_client_failure(exit_code) {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(LsbxError::BackendUnavailable(format!(
            "ssh could not reach guest '{}': {}",
            target.host,
            stderr.trim()
        )));
    }

    Ok(lsbx_kernel::backend::CommandOutput {
        exit_code: exit_code.unwrap_or(-1),
        stdout: output.stdout,
        stderr: output.stderr,
    })
}

/// Copies `source` (local) to `destination` (a remote path inside the
/// guest) via batch-mode `scp`, stdin isolated the same way as
/// [`run_command`].
pub async fn put_file(
    target: &GuestSshTarget<'_>,
    source: &Path,
    destination: &str,
) -> Result<(), LsbxError> {
    let mut args = base_ssh_args(target);
    args.push(source.as_os_str().to_owned());
    args.push(format!("{}@{}:{}", target.username, target.host, destination).into());
    run_scp(&args, target.host).await
}

/// Copies `source` (a remote path inside the guest) to `destination`
/// (local) via batch-mode `scp`, stdin isolated the same way as
/// [`run_command`].
pub async fn get_file(
    target: &GuestSshTarget<'_>,
    source: &str,
    destination: &Path,
) -> Result<(), LsbxError> {
    let mut args = base_ssh_args(target);
    args.push(format!("{}@{}:{}", target.username, target.host, source).into());
    args.push(destination.as_os_str().to_owned());
    run_scp(&args, target.host).await
}

async fn run_scp(args: &[std::ffi::OsString], host: &str) -> Result<(), LsbxError> {
    let output = Command::new("scp")
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await
        .map_err(|e| LsbxError::BackendUnavailable(format!("failed to spawn scp: {e}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if is_ssh_client_failure(output.status.code()) {
            return Err(LsbxError::BackendUnavailable(format!(
                "scp could not reach guest '{host}': {}",
                stderr.trim()
            )));
        }
        return Err(LsbxError::ContractViolated(format!(
            "scp transfer failed: {}",
            stderr.trim()
        )));
    }

    Ok(())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn base_ssh_args_always_include_batch_mode() {
        let target = GuestSshTarget {
            host: "192.0.2.1",
            username: "lsbx",
            identity_file: Path::new("/tmp/fake-key"),
        };
        let args: Vec<String> = base_ssh_args(&target)
            .into_iter()
            .map(|s| s.to_string_lossy().into_owned())
            .collect();
        assert!(args.contains(&"BatchMode=yes".to_string()));
    }

    #[test]
    fn base_ssh_args_use_accept_new_not_disabled_host_key_checking() {
        let target = GuestSshTarget {
            host: "192.0.2.1",
            username: "lsbx",
            identity_file: Path::new("/tmp/fake-key"),
        };
        let args: Vec<String> = base_ssh_args(&target)
            .into_iter()
            .map(|s| s.to_string_lossy().into_owned())
            .collect();
        assert!(args.contains(&"StrictHostKeyChecking=accept-new".to_string()));
        assert!(!args.iter().any(|a| a == "StrictHostKeyChecking=no"));
    }

    #[test]
    fn ssh_client_failure_exit_code_255_is_recognized() {
        assert!(is_ssh_client_failure(Some(255)));
        assert!(!is_ssh_client_failure(Some(0)));
        assert!(!is_ssh_client_failure(Some(1)));
        assert!(!is_ssh_client_failure(None));
    }

    #[test]
    fn shell_quote_leaves_safe_words_unquoted() {
        assert_eq!(shell_quote("git"), "git");
        assert_eq!(shell_quote("python3"), "python3");
        assert_eq!(shell_quote("web-search"), "web-search");
    }

    #[test]
    fn shell_quote_quotes_spaces_and_singletons() {
        assert_eq!(shell_quote("git --version"), "'git --version'");
        assert_eq!(shell_quote(""), "''");
        assert_eq!(shell_quote("a'b"), "'a'\\''b'");
    }

    #[test]
    fn shell_quote_join_preserves_argv_for_sh_c() {
        // The canonical healthcheck shape `["sh", "-c", "git --version"]`
        // must round-trip into one shell command line that the guest parses
        // back as `sh -c 'git --version'` — not `sh -c git --version`.
        assert_eq!(
            shell_quote_join(&[
                "sh".to_string(),
                "-c".to_string(),
                "git --version".to_string(),
            ]),
            "sh -c 'git --version'"
        );
        assert_eq!(shell_quote_join(&["true".to_string()]), "true");
    }

    /// The named acceptance scenario from the unit contract: a remote
    /// command spawned by this backend must have its stdin connected to
    /// `/dev/null` (or an equivalently verifiable non-inherited state),
    /// never the parent process's stdin. This drives the exact
    /// `run_command` code path (not a standalone `ssh` invocation
    /// unconnected to the library, unlike both source candidates' test
    /// files) against a fake `ssh`-shaped script substituted onto PATH, so
    /// the assertion is about *this module's* spawn configuration, not
    /// about OpenSSH's own behavior.
    #[tokio::test]
    async fn run_command_isolates_stdin_from_dev_null() {
        // Build a fake `ssh` that reports whether its own stdin is at EOF
        // immediately (which is exactly what happens when stdin is
        // `/dev/null`) vs. blocked waiting for input (what would happen if
        // it inherited a live pipe). A real inherited terminal/pipe stdin
        // would not be at immediate EOF; `/dev/null` always is.
        let dir = tempfile_dir();
        let fake_ssh_path = dir.join("ssh");
        std::fs::write(
            &fake_ssh_path,
            "#!/bin/sh\nif read -t 0.2 _line; then\n  echo \"stdin was NOT at EOF\" >&2\n  exit 1\nelse\n  echo \"stdin was at EOF (isolated)\"\n  exit 0\nfi\n",
        )
        .expect("write fake ssh script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&fake_ssh_path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod fake ssh script");
        }

        let original_path = std::env::var("PATH").unwrap_or_default();
        let new_path = format!("{}:{original_path}", dir.to_string_lossy());

        let target = GuestSshTarget {
            host: "192.0.2.1",
            username: "lsbx",
            identity_file: Path::new("/tmp/fake-key"),
        };

        // SAFETY-equivalent note: this mutates process-wide PATH for the
        // duration of this test. Acceptable here because this crate's test
        // binaries run single-threaded-enough for this specific test not to
        // race another test's own PATH-sensitive subprocess spawn — see
        // the `#[serial]`-equivalent isolation via a dedicated temp PATH
        // prefix rather than relying on test ordering.
        std::env::set_var("PATH", &new_path);
        let result = run_command(
            &target,
            &["irrelevant".to_string()],
            std::time::Duration::from_secs(5),
        )
        .await;
        std::env::set_var("PATH", original_path);

        let output = result.expect("fake ssh script should have run successfully");
        assert_eq!(output.exit_code, 0);
        assert!(String::from_utf8_lossy(&output.stdout).contains("isolated"));
    }

    fn tempfile_dir() -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "lsbx-guest-ssh-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::create_dir_all(&dir).expect("create temp dir for fake ssh script");
        dir
    }
}
